apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: gcr.io/fashfrenzy/node-app:v2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: fashfrenzy-app-service
spec:
  selector:
    app: fashfrenzy
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: LoadBalancer
