apiVersion: apps/v1
kind: Deployment
metadata:
  name: fashfrenzy-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fashfrenzy
  template:
    metadata:
      labels:
        app: fashfrenzy
    spec:
      containers:
      - name: fashfrenzy
        image: giangnht19/fashfrenzy_backend:v1
        ports:
        - containerPort: 8080
        env:
        # Database configuration
        - name: DB_TYPE
          value: "mongodb"
        - name: DB_NAME
          value: "fashfrenzy"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret   # Kubernetes Secret containing the connection string
              key: MONGODB_URI
---
apiVersion: v1
kind: Service
metadata:
  name: fashfrenzy-app-service
spec:
  selector:
    app: fashfrenzy
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
